[env]
_.path = ['{{config_root}}/node_modules/.bin']

[settings]
# enable .nvmrc support for node
idiomatic_version_file_enable_tools = ["node"]

[tools]
# apps
"npm:@anthropic-ai/claude-code" = "latest"

# mcp servers
"npm:@upstash/context7-mcp" = "latest"
"pipx:wrale/mcp-server-tree-sitter" = "latest"

# core tools
bun = "1.3.1"
go = "1.25.3"
node = "25.1.0"
terraform = "1.13.4"
