[env]
_.path = ['{{config_root}}/node_modules/.bin']

[settings]
experimental = true

# enable .nvmrc support for node
idiomatic_version_file_enable_tools = ["node"]

# enable lockfile
lockfile = true

# use bun
npm.bun = true

[tools]
# apps
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@github/copilot" = "latest"
"npm:opencode-ai" = "latest"
"npm:vibe-kanban" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"

# go tools
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

# mcp servers
"npm:@sveltejs/mcp" = "latest"
"npm:@upstash/context7-mcp" = "latest"
"npm:chrome-devtools-mcp" = "latest"

# core tools
bun = "latest"
go = "latest"
node = "latest"
terraform = "latest"

# other
"npm:@ast-grep/cli" = "latest"
